# Generated by Django 5.2.17 on 2026-08-31 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmLocalRecord',
            fields=[
                ('crm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hubspot_contact_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('lead_score', models.IntegerField(default=0)),
                ('segment', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot_lead', 'Hot Lead')], default='cold', max_length=10)),
                ('preferences_data', models.JSONField(blank=True, default=dict, help_text='Preferencias sensoriales detectadas por AI Concierge')),
                ('last_synced_hubspot', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_record', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='HotelDelivery',
            fields=[
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(default='Quito', max_length=100)),
                ('hotel_name', models.CharField(db_index=True, max_length=255)),
                ('guest_name', models.CharField(max_length=255)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('hotel_reception', 'Reception'), ('hotel_room', 'Room')], default='hotel_reception', max_length=20)),
                ('delivery_status', models.CharField(choices=[('reservado', 'Reservado'), ('en_preparacion', 'En Preparacion'), ('entregado', 'Entregado'), ('confirmado', 'Confirmado')], db_index=True, default='reservado', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_delivery', to='commerce.order')),
            ],
            options={
                'verbose_name_plural': 'Hotel deliveries',
            },
        ),
    ]
