# Generated by Django 5.2.17 on 2026-08-31 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('collection_type', models.CharField(choices=[('bars', 'Bars'), ('romantic', 'Romantic'), ('corporate', 'Corporate'), ('premium', 'Premium'), ('limited', 'Limited'), ('exclusive_handicrafts', 'Handicrafts')], db_index=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cocoa_percentage', models.IntegerField(blank=True, null=True)),
                ('flavor_profile', models.CharField(choices=[('chili', 'Chili'), ('coffee', 'Coffee'), ('dark', 'Dark'), ('salt', 'Salt'), ('none', 'None')], default='none', max_length=10)),
                ('customization_data', models.JSONField(blank=True, default=dict, help_text='Variantes y configuraciones dinamicas del producto')),
                ('builder_content_id', models.CharField(blank=True, db_index=True, help_text='Referencia al contenido asociado en Builder.io DXP', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
